import { describe, expect, it } from "vitest";
import { parseSqlOut, parseStructSchema } from "./helpers/spark-sqltests.js";

// Unit tests for the Spark sql-tests golden-file parser (tests/helpers/spark-sqltests.ts).
// The .sql.out files are "Automatically generated by SQLQueryTestSuite": per query a
// `-- !query` block with the SQL, a `-- !query schema` line carrying Spark's analyzer
// output schema (struct<name:type,...>), and a `-- !query output` block. The schema
// parser must never mis-split a field: on anything it cannot round-trip byte-exactly it
// answers undefined (the gate counts those instead of grading them wrong).

describe("parseStructSchema", () => {
	it("parses a simple schema", () => {
		expect(parseStructSchema("struct<key:int,value:string>")).toEqual([
			{ name: "key", type: "int" },
			{ name: "value", type: "string" },
		]);
	});

	it("parses Spark's pretty-printed expression names", () => {
		expect(parseStructSchema("struct<(- key):int,(+ key):int>")).toEqual([
			{ name: "(- key)", type: "int" },
			{ name: "(+ key)", type: "int" },
		]);
	});

	it("keeps a comparison's < inside parens out of the bracket depth", () => {
		expect(parseStructSchema("struct<(1 < 2):boolean,(a > b):boolean>")).toEqual([
			{ name: "(1 < 2)", type: "boolean" },
			{ name: "(a > b)", type: "boolean" },
		]);
	});

	it("ignores colons and commas inside quoted literals in names", () => {
		expect(parseStructSchema("struct<TIMESTAMP '2019-01-01 00:00:00':timestamp>")).toEqual([
			{ name: "TIMESTAMP '2019-01-01 00:00:00'", type: "timestamp" },
		]);
		expect(parseStructSchema("struct<str_to_map(a, ',', ':'):map<string,string>>")).toEqual([
			{ name: "str_to_map(a, ',', ':')", type: "map<string,string>" },
		]);
	});

	it("parses parenthesized and nested generic types", () => {
		expect(parseStructSchema("struct<-5.2:decimal(2,1)>")).toEqual([{ name: "-5.2", type: "decimal(2,1)" }]);
		expect(parseStructSchema("struct<arr:array<struct<a:int,b:string>>,m:map<int,array<string>>>")).toEqual([
			{ name: "arr", type: "array<struct<a:int,b:string>>" },
			{ name: "m", type: "map<int,array<string>>" },
		]);
	});

	it("answers [] for the empty schema and undefined for non-struct lines", () => {
		expect(parseStructSchema("struct<>")).toEqual([]);
		expect(parseStructSchema("org.apache.spark.sql.AnalysisException")).toBeUndefined();
	});

	it("answers undefined (never a wrong split) when the field text cannot round-trip", () => {
		// A raw `<` in a name at depth 0 (backtick-quoted alias upstream) unbalances the walk.
		expect(parseStructSchema("struct<a<b:int>")).toBeUndefined();
	});
});

describe("parseSqlOut", () => {
	const sample = [
		"-- Automatically generated by SQLQueryTestSuite",
		"-- !query",
		"select -100",
		"-- !query schema",
		"struct<-100:int>",
		"-- !query output",
		"-100",
		"",
		"",
		"-- !query",
		"select key, value",
		"from testdata",
		"-- !query schema",
		"struct<key:int,value:string>",
		"-- !query output",
		"1\ta",
		"",
	].join("\n");

	it("splits records and keeps multi-line SQL", () => {
		const recs = parseSqlOut(sample);
		expect(recs).toHaveLength(2);
		expect(recs[0]).toMatchObject({ sql: "select -100", schemaRaw: "struct<-100:int>" });
		expect(recs[0].fields).toEqual([{ name: "-100", type: "int" }]);
		expect(recs[1].sql).toBe("select key, value\nfrom testdata");
		expect(recs[1].fields).toEqual([
			{ name: "key", type: "int" },
			{ name: "value", type: "string" },
		]);
	});

	it("keeps a DDL/command record with the empty schema, fields []", () => {
		const ddl = ["-- !query", "create temporary view v as select 1", "-- !query schema", "struct<>", "-- !query output", "", ""].join(
			"\n",
		);
		const recs = parseSqlOut(ddl);
		expect(recs).toHaveLength(1);
		expect(recs[0].fields).toEqual([]);
	});
});
