import { parseType, scalar, UNKNOWN, type Type } from "../infer/types.js";
import type { FnRule } from "../infer/functions.js";
import { commonType } from "../infer/coerce.js";
import { fold } from "./fold.js";

// ---------------------------------------------------------------------------
// DuckDB inference knowledge. Scalar-name aliases map DuckDB's type vocabulary
// onto the shared canonical names (duckdb.org/docs/current/sql/data_types/
// overview.md — the alias table there); `/` is ALWAYS float division, `//` is
// integer division (sql/functions/numeric.md: "Division. Returns DOUBLE even
// for integer inputs"). Function returns doc-cited against the DuckDB function
// reference (duckdb.org/docs/current/sql/functions/…, per-family pages noted
// below). A missing entry safely yields `unknown` — never guess.
// ---------------------------------------------------------------------------

export const DUCKDB_ALIASES: Record<string, string> = {
	int1: "tinyint",
	int2: "smallint",
	short: "smallint",
	int4: "int",
	integer: "int",
	signed: "int",
	int8: "bigint",
	long: "bigint",
	hugeint: "hugeint",
	ubigint: "bigint",
	uinteger: "int",
	usmallint: "smallint",
	utinyint: "tinyint",
	numeric: "decimal",
	dec: "decimal",
	float4: "float",
	real: "float",
	float8: "double",
	float: "float", // bare FLOAT is single-precision in DuckDB (data_types/numeric.md)
	"double precision": "double",
	bool: "boolean",
	logical: "boolean",
	char: "string",
	bpchar: "string",
	varchar: "string",
	text: "string",
	blob: "binary",
	bytea: "binary",
	varbinary: "binary",
	timestamptz: "timestamp",
	"timestamp with time zone": "timestamp",
	"timestamp without time zone": "timestamp",
	datetime: "timestamp",
	timetz: "time",
	uuid: "uuid",
	json: "json",
};

export function duckdbParseType(text: string): Type {
	return parseType(text, DUCKDB_ALIASES, fold);
}

const S = scalar("string");
const I = scalar("int");
const BIG = scalar("bigint");
const HUGE = scalar("hugeint");
const D = scalar("double");
const DEC = scalar("decimal");
const B = scalar("boolean");
const DATE = scalar("date");
const TIME = scalar("time");
const TS = scalar("timestamp");
const IV = scalar("interval");
const BIN = scalar("binary");
const JSON_T = scalar("json");
const UUID = scalar("uuid");
const SARR = { kind: "array", element: S } as const satisfies Type;

/** DuckDB literal forms — sql/data_types/literal_types.md: integers without a decimal point are
 *  INTEGER-family; a decimal point makes a DECIMAL; E-notation makes a DOUBLE; strings are
 *  VARCHAR. Underscore digit separators allowed. */
export function duckdbLiteral(text: string): Type {
	const t = text.trim();
	if (/^[eE]?'/.test(t) || /^\$[a-zA-Z_0-9]*\$/.test(t)) return S;
	if (/^[bB]'/.test(t)) return scalar("bit");
	if (/^[xX]'/.test(t)) return BIN;
	if (/^(true|false)$/i.test(t)) return B;
	if (/^null$/i.test(t)) return UNKNOWN;
	if (/^date\s*'/i.test(t)) return DATE;
	if (/^time\s*'/i.test(t)) return TIME;
	if (/^timestamp/i.test(t) && /'/.test(t)) return TS;
	if (/^interval\b/i.test(t)) return IV;
	if (/^[+-]?\d[\d_]*$/.test(t)) return I;
	if (/^[+-]?(\d[\d_]*\.?[\d_]*|\.[\d_]+)e[+-]?\d+$/i.test(t)) return D;
	if (/^[+-]?(\d[\d_]*\.[\d_]*|\.[\d_]+)$/.test(t)) return DEC;
	if (/^0[xX][0-9a-fA-F_]+$/.test(t) || /^0[bB][01_]+$/.test(t)) return I;
	return UNKNOWN;
}

const fixed =
	(t: Type): FnRule =>
	() =>
		t;
const firstArg: FnRule = (args) => args[0] ?? UNKNOWN;
const common: FnRule = (args) => commonType(args);
const listOfFirst: FnRule = (args) => ({ kind: "array", element: args[0] ?? UNKNOWN });
const elementOfFirst: FnRule = (args) => (args[0]?.kind === "array" ? args[0].element : UNKNOWN);

function group(rule: FnRule, names: string[]): Record<string, FnRule> {
	return Object.fromEntries(names.map((n) => [n, rule]));
}

/** sum() — functions/aggregates.md: HUGEINT for integer inputs, DOUBLE for float, keeps
 *  DECIMAL. */
const sumRule: FnRule = (args) => {
	const a = args[0];
	if (a?.kind !== "scalar") return UNKNOWN;
	if (["tinyint", "smallint", "int", "bigint", "hugeint", "boolean"].includes(a.name)) return HUGE;
	if (a.name === "decimal") return DEC;
	return D;
};

export const DUCKDB_FUNCTION_RETURNS: Record<string, FnRule> = {
	// --- numeric — sql/functions/numeric.md -------------------------------------
	...group(firstArg, [
		"abs",
		"ceil",
		"ceiling",
		"floor",
		"round",
		"trunc",
		"sign",
		"even",
		"gcd",
		"lcm",
		"greatest_common_divisor",
		"least_common_multiple",
	]),
	...group(fixed(D), [
		"cbrt",
		"degrees",
		"radians",
		"pi",
		"random",
		"exp",
		"ln",
		"log",
		"log2",
		"log10",
		"sqrt",
		"pow",
		"power",
		"atan2",
		"sin",
		"cos",
		"tan",
		"cot",
		"asin",
		"acos",
		"atan",
		"sinh",
		"cosh",
		"tanh",
		"asinh",
		"acosh",
		"atanh",
		"gamma",
		"lgamma",
	]),
	fdiv: fixed(D),
	fmod: fixed(D),
	factorial: fixed(HUGE),
	divide: fixed(BIG),
	xor: firstArg,
	bit_count: fixed(I),
	setseed: fixed(UNKNOWN),
	isnan: fixed(B),
	isinf: fixed(B),
	isfinite: fixed(B),
	nextafter: fixed(D),
	// --- text — sql/functions/text.md -------------------------------------------
	...group(fixed(S), [
		"concat",
		"concat_ws",
		"format",
		"printf",
		"lower",
		"lcase",
		"upper",
		"ucase",
		"left",
		"right",
		"lpad",
		"rpad",
		"ltrim",
		"rtrim",
		"trim",
		"repeat",
		"replace",
		"reverse",
		"substr",
		"substring",
		"substring_grapheme",
		"string_split_regex_part",
		"split_part",
		"translate",
		"to_base",
		"chr",
		"md5",
		"initcap",
		"title",
		"nfc_normalize",
		"strip_accents",
		"bar",
		"to_hex",
		"to_binary",
		"from_base64_string",
		"url_encode",
		"url_decode",
		"format_bytes",
		"formatreadabledecimalsize",
		"left_grapheme",
		"right_grapheme",
	]),
	...group(fixed(I), [
		"ascii",
		"instr",
		"strpos",
		"position",
		"levenshtein",
		"editdist3",
		"hamming",
		"mismatches",
		"damerau_levenshtein",
		"strlen",
		"length",
		"char_length",
		"character_length",
		"length_grapheme",
		"bit_length",
		"octet_length",
		"unicode",
		"ord",
	]),
	...group(fixed(D), ["jaccard", "jaro_similarity", "jaro_winkler_similarity"]),
	...group(fixed(B), [
		"contains",
		"starts_with",
		"ends_with",
		"suffix",
		"prefix",
		"regexp_matches",
		"regexp_full_match",
		"like_escape",
		"ilike_escape",
		"not_like_escape",
		"not_ilike_escape",
	]),
	...group(fixed(S), ["regexp_replace", "regexp_extract", "regexp_escape"]),
	regexp_extract_all: fixed(SARR),
	string_split: fixed(SARR),
	str_split: fixed(SARR),
	string_split_regex: fixed(SARR),
	string_to_array: fixed(SARR),
	split: fixed(SARR),
	hash: fixed(BIG),
	from_base64: fixed(BIN),
	to_base64: fixed(S),
	base64: fixed(S),
	encode: fixed(BIN),
	decode: fixed(S),
	// --- date/time — sql/functions/date.md, timestamp.md, interval.md -----------
	...group(fixed(TS), [
		"now",
		"get_current_timestamp",
		"transaction_timestamp",
		"make_timestamp",
		"make_timestamptz",
		"to_timestamp",
		"strptime",
		"try_strptime",
		"date_add",
	]),
	current_date: fixed(DATE),
	today: fixed(DATE),
	get_current_time: fixed(TIME),
	current_localtime: fixed(TIME),
	current_localtimestamp: fixed(TS),
	make_date: fixed(DATE),
	make_time: fixed(TIME),
	...group(fixed(BIG), [
		"date_diff",
		"datediff",
		"date_sub",
		"datesub",
		"epoch",
		"epoch_ms",
		"epoch_us",
		"epoch_ns",
		"nanosecond",
	]),
	...group(fixed(BIG), [
		"century",
		"day",
		"dayofmonth",
		"dayofweek",
		"dayofyear",
		"decade",
		"era",
		"hour",
		"isodow",
		"isoyear",
		"julian",
		"microsecond",
		"millennium",
		"millisecond",
		"minute",
		"month",
		"quarter",
		"second",
		"timezone",
		"timezone_hour",
		"timezone_minute",
		"week",
		"weekday",
		"weekofyear",
		"year",
		"yearweek",
	]),
	date_part: fixed(BIG), // functions/date.md — BIGINT part values
	datepart: fixed(BIG),
	extract: fixed(BIG),
	date_trunc: (args) => args[1] ?? TS,
	datetrunc: (args) => args[1] ?? TS,
	time_bucket: firstArg,
	...group(fixed(S), ["dayname", "monthname", "strftime"]),
	...group(fixed(IV), [
		"age",
		"to_years",
		"to_months",
		"to_weeks",
		"to_days",
		"to_hours",
		"to_minutes",
		"to_seconds",
		"to_milliseconds",
		"to_microseconds",
		"to_centuries",
		"to_decades",
		"to_millennia",
	]),
	last_day: fixed(DATE),
	greatest: common,
	least: common,
	// --- list — sql/functions/list.md --------------------------------------------
	...group(firstArg, [
		"list_sort",
		"list_reverse_sort",
		"list_reverse",
		"list_distinct",
		"list_resize",
		"array_distinct",
		"list_slice",
		"array_slice",
		"list_concat",
		"list_cat",
		"array_concat",
		"array_cat",
		"flatten",
		"list_grade_up",
	]),
	...group(elementOfFirst, [
		"list_extract",
		"list_element",
		"array_extract",
		"list_first",
		"list_last",
		"list_any_value",
		"list_max",
		"list_min",
	]),
	...group(fixed(BIG), [
		"list_position",
		"list_indexof",
		"array_position",
		"array_indexof",
		"len",
		"array_length",
		"list_unique",
		"array_unique",
	]),
	...group(fixed(B), [
		"list_contains",
		"array_contains",
		"list_has",
		"array_has",
		"list_has_any",
		"array_has_any",
		"list_has_all",
		"array_has_all",
	]),
	list_value: listOfFirst,
	list_pack: listOfFirst,
	list_append: firstArg,
	list_prepend: (args) => args[1] ?? UNKNOWN,
	list_aggregate: fixed(UNKNOWN), // result depends on the named aggregate
	list_transform: fixed({ kind: "array", element: UNKNOWN }),
	list_filter: firstArg,
	list_reduce: fixed(UNKNOWN),
	list_zip: fixed({ kind: "array", element: UNKNOWN }),
	array_to_string: fixed(S),
	list_string_agg: fixed(S),
	range: fixed({ kind: "array", element: BIG }),
	generate_series: fixed({ kind: "array", element: BIG }),
	unnest: elementOfFirst,
	list_dot_product: fixed(D),
	list_cosine_similarity: fixed(D),
	list_distance: fixed(D),
	list_inner_product: fixed(D),
	repeat_list: firstArg,
	// --- struct / map / union — struct.md, map.md, union.md ----------------------
	struct_pack: fixed(UNKNOWN), // a struct of the given fields — schemaless here
	struct_insert: firstArg,
	struct_extract: fixed(UNKNOWN),
	row: fixed(UNKNOWN),
	map: fixed(UNKNOWN),
	map_from_entries: fixed(UNKNOWN),
	map_extract: fixed(UNKNOWN),
	map_values: fixed({ kind: "array", element: UNKNOWN }),
	map_keys: fixed({ kind: "array", element: UNKNOWN }),
	map_entries: fixed({ kind: "array", element: UNKNOWN }),
	cardinality: fixed(BIG),
	element_at: fixed(UNKNOWN),
	union_extract: fixed(UNKNOWN),
	union_value: fixed(UNKNOWN),
	union_tag: fixed(S),
	// --- aggregates — sql/functions/aggregates.md --------------------------------
	count: fixed(BIG),
	count_star: fixed(BIG),
	count_if: fixed(BIG),
	countif: fixed(BIG),
	sum: sumRule,
	fsum: fixed(D),
	sumkahan: fixed(D),
	kahan_sum: fixed(D),
	avg: fixed(D),
	mean: fixed(D),
	favg: fixed(D),
	geomean: fixed(D),
	geometric_mean: fixed(D),
	min: firstArg,
	max: firstArg,
	arg_max: firstArg,
	arg_min: firstArg,
	argmax: firstArg,
	argmin: firstArg,
	max_by: firstArg,
	min_by: firstArg,
	first: firstArg,
	last: firstArg,
	any_value: firstArg,
	arbitrary: firstArg,
	list: listOfFirst,
	array_agg: listOfFirst,
	histogram: fixed(UNKNOWN), // MAP(input, UBIGINT)
	string_agg: fixed(S),
	listagg: fixed(S),
	group_concat: fixed(S),
	bit_and: firstArg,
	bit_or: firstArg,
	bit_xor: firstArg,
	bitstring_agg: fixed(scalar("bit")),
	bool_and: fixed(B),
	bool_or: fixed(B),
	product: fixed(D),
	...group(fixed(D), [
		"corr",
		"covar_pop",
		"covar_samp",
		"stddev",
		"stddev_pop",
		"stddev_samp",
		"var_pop",
		"var_samp",
		"variance",
		"entropy",
		"kurtosis",
		"kurtosis_pop",
		"skewness",
		"mad",
		"regr_avgx",
		"regr_avgy",
		"regr_intercept",
		"regr_r2",
		"regr_slope",
		"regr_sxx",
		"regr_sxy",
		"regr_syy",
	]),
	regr_count: fixed(BIG),
	median: firstArg,
	mode: firstArg,
	quantile: firstArg,
	quantile_cont: firstArg,
	quantile_disc: firstArg,
	approx_quantile: firstArg,
	reservoir_quantile: firstArg,
	approx_count_distinct: fixed(BIG),
	// --- window — sql/functions/window_functions.md -------------------------------
	row_number: fixed(BIG),
	rank: fixed(BIG),
	rank_dense: fixed(BIG),
	dense_rank: fixed(BIG),
	percent_rank: fixed(D),
	cume_dist: fixed(D),
	ntile: fixed(BIG),
	lag: firstArg,
	lead: firstArg,
	first_value: firstArg,
	last_value: firstArg,
	nth_value: firstArg,
	// --- json — data/json/json_functions.md ---------------------------------------
	...group(fixed(JSON_T), [
		"json",
		"json_quote",
		"json_array",
		"json_object",
		"json_merge_patch",
		"json_extract",
		"json_extract_path",
		"to_json",
		"row_to_json",
		"array_to_json",
		"json_group_array",
		"json_group_object",
		"json_group_structure",
		"json_serialize_sql",
		"json_deserialize_sql",
	]),
	...group(fixed(S), [
		"json_extract_string",
		"json_extract_path_text",
		"json_type",
		"json_typeof",
		"json_structure",
		"json_pretty",
	]),
	json_array_length: fixed(BIG),
	json_keys: fixed(SARR),
	json_valid: fixed(B),
	json_contains: fixed(B),
	json_exists: fixed(B),
	json_value: fixed(S),
	// --- utility / system — sql/functions/utility.md -------------------------------
	coalesce: common,
	nullif: firstArg,
	ifnull: common,
	if: (args) => commonType(args.slice(1)),
	...group(fixed(S), [
		"current_catalog",
		"current_database",
		"current_schema",
		"current_user",
		"user",
		"session_user",
		"version",
		"typeof",
		"current_setting",
		"getenv",
		"alias",
		"current_query",
		"txid_current_str",
	]),
	current_schemas: fixed(SARR),
	gen_random_uuid: fixed(UUID),
	uuid: fixed(UUID),
	uuidv4: fixed(UUID),
	uuidv7: fixed(UUID),
	uuid_extract_timestamp: fixed(TS),
	uuid_extract_version: fixed(I),
	txid_current: fixed(BIG),
	pg_typeof: fixed(S),
	error: fixed(UNKNOWN),
	getvariable: fixed(UNKNOWN), // the stored variable's own type
	constant_or_null: firstArg,
	stats: fixed(S),
	icu_sort_key: fixed(S),
	// --- bit / blob — sql/functions/bitstring.md, blob.md --------------------------
	get_bit: fixed(I),
	set_bit: firstArg,
	bit_position: fixed(I),
	bitstring: fixed(scalar("bit")),
	octet_length_blob: fixed(BIG),
	// --- enum — sql/functions/enum.md ----------------------------------------------
	enum_first: fixed(S),
	enum_last: fixed(S),
	enum_code: fixed(I),
	enum_range: fixed(SARR),
	enum_range_boundary: fixed(SARR),
};
