// ---------------------------------------------------------------------------
// Parser for apache/spark's sql-tests golden files (vendor/spark/sql-tests/
// results/**/*.sql.out in the corpus repo). Each file is "Automatically
// generated by SQLQueryTestSuite": per query a `-- !query` block (the SQL),
// a `-- !query schema` line carrying Spark's OWN analyzer output schema
// (struct<name:type,...>), and a `-- !query output` block (result rows, or an
// exception rendering). The schema line is the external truth the
// databricks.sqltests corpus gate grades our analyze() types against.
//
// Never-wrong at the parser level: a schema field list is returned ONLY when
// re-joining the parsed fields reproduces the input byte-exactly (round-trip
// guard). Anything else (error renderings, exotic names the walk cannot
// balance, e.g. a backtick-quoted alias containing a bare `<`) answers
// undefined, and the gate counts those records instead of grading them.
// ---------------------------------------------------------------------------

export interface SchemaField {
	/** Spark's rendered output column name; unaliased expressions are pretty-printed (`(+ key)`). */
	name: string;
	/** Spark's type string, lowercase (`int`, `decimal(2,1)`, `array<struct<a:int>>`). */
	type: string;
}

export interface SqlTestRecord {
	/** The query text, possibly multi-line, as written in the golden file. */
	sql: string;
	/** The raw `-- !query schema` payload (usually `struct<...>`, sometimes an error rendering). */
	schemaRaw: string;
	/** Parsed fields; `[]` for `struct<>` (DDL/commands); undefined when unparseable. */
	fields: SchemaField[] | undefined;
	/** The `-- !query output` payload (rows or an exception rendering). */
	output: string;
}

/**
 * Parse one `struct<name:type,...>` schema line into fields, or undefined when the
 * line is not a cleanly parseable struct rendering. Field separators are commas at
 * bracket depth 0; the name/type split is the LAST depth-0 colon (names may contain
 * colons inside quoted literals, and types never contain a bare depth-0 colon).
 * `<`/`>` count toward depth only at paren depth 0 (a name like `(1 < 2)` keeps its
 * comparison operators out of the generic-bracket balance); single-quoted spans
 * neutralize everything inside them.
 */
export function parseStructSchema(s: string): SchemaField[] | undefined {
	if (!s.startsWith("struct<") || !s.endsWith(">")) return undefined;
	const inner = s.slice("struct<".length, -1);
	if (inner === "") return [];

	const fields: SchemaField[] = [];
	let paren = 0;
	let angle = 0;
	let quote = false;
	let fieldStart = 0;
	let lastColon = -1;

	const flush = (end: number): boolean => {
		if (lastColon < 0) return false;
		fields.push({ name: inner.slice(fieldStart, lastColon), type: inner.slice(lastColon + 1, end) });
		return true;
	};

	for (let i = 0; i < inner.length; i++) {
		const c = inner[i];
		if (quote) {
			if (c === "'") quote = false;
			continue;
		}
		if (c === "'") quote = true;
		else if (c === "(") paren++;
		else if (c === ")") paren--;
		else if (c === "<") {
			if (paren === 0) angle++;
		} else if (c === ">") {
			if (paren === 0) angle--;
		} else if (c === "," && paren === 0 && angle === 0) {
			if (!flush(i)) return undefined;
			fieldStart = i + 1;
			lastColon = -1;
		} else if (c === ":" && paren === 0 && angle === 0) {
			lastColon = i;
		}
		if (paren < 0 || angle < 0) return undefined;
	}
	if (quote || paren !== 0 || angle !== 0) return undefined;
	if (!flush(inner.length)) return undefined;

	// Round-trip guard: a mis-split must never survive as a wrong field list.
	if (fields.map((f) => `${f.name}:${f.type}`).join(",") !== inner) return undefined;
	return fields;
}

/** Parse a whole `.sql.out` file into its records. Truncated trailing records are dropped. */
export function parseSqlOut(text: string): SqlTestRecord[] {
	const lines = text.split(/\r?\n/);
	const records: SqlTestRecord[] = [];
	let i = 0;

	const collect = (stop: (line: string) => boolean): string[] => {
		const out: string[] = [];
		while (i < lines.length && !stop(lines[i])) out.push(lines[i++]);
		return out;
	};

	while (i < lines.length) {
		if (lines[i].trim() !== "-- !query") {
			i++;
			continue;
		}
		i++;
		const sql = collect((l) => l.trim() === "-- !query schema").join("\n").trim();
		if (i >= lines.length) break;
		i++;
		const schemaRaw = collect((l) => l.trim() === "-- !query output").join("\n").trim();
		if (i >= lines.length) break;
		i++;
		const output = collect((l) => l.trim() === "-- !query").join("\n").replace(/\n+$/, "");
		records.push({ sql, schemaRaw, fields: parseStructSchema(schemaRaw), output });
	}
	return records;
}
